### ISSUE TITLE
Issues with deploy_app

### ISSUE THREAD

**Issue by jongio** [Azure-Samples/functions-storage-managed-identity#1]
If you run the terraform apply command on Windows and then run the sh file in WSL, you get the following due to line endings

```
./deploy_app.sh: line 2: $'\r': command not found
./deploy_app.sh: line 3: az: command not found
./deploy_app.sh: line 4: func: command not found
./deploy_app.sh: line 4: cd: $'../terraform\r': No such file or directory
```
If you fix the line endings, you get:

```
./deploy_app.sh: line 3: az: command not found
./deploy_app.sh: line 4: func: command not found
```

When you run with Git Bash you get the following because az isn't mapped.

```
$ ./deploy_app.sh
./deploy_app.sh: line 3: az: command not found
```

I resolved with: https://stackoverflow.com/a/58765679

I recommend showing user how to get around that and also consider creating a .cmd file.

**Comment by brandonh-msft** [comment]
since all of these are resolved by simply using the provided devcontainer, I don't plan on fixing this.
