### ISSUE TITLE
ElasticPremium plans

### ISSUE THREAD

**Issue by phatcher** [Azure-Samples/functions-storage-managed-identity#3]
If we want to Managed Identity and ElasticPremium plans do we also need `Storage File Data SMB Share Contributor` and/or `Storage Queue Data Contributor` rights?

**Comment by brandonh-msft** [comment]
Those rights are dependent on what you're _doing_ with the plan; not the type of plan onto which the Functions are deployed.
So for SMB, the answer is 'yes' if you want your Function to be putting data into an Azure Files share on a Storage account.
For the second, similarly, if you're adding data to a Storage Queue the answer is 'yes'.

Fora the purposes of this sample, the answer to both is 'no.'
