### ISSUE TITLE
If managed identity is really being used, why the primary access key of storage account is still used in function creation??

### ISSUE THREAD

**Issue by kiranpradeep** [Azure-Samples/functions-storage-managed-identity#4]
In infra creation terraform file line 84 ([link](https://github.com/Azure-Samples/functions-storage-managed-identity/blob/3297b2304628357b16596d4f03d9a53765211ab2/terraform/main.tf#L84)), the storage acccount primary access key is still used for [creation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#storage_account_access_key). The advantage of managed identity was that we would not need to save access key. This defeats the purpose of managed identity. Am I missing anything here?

For e.g. in this Azure Function accessing Azure SQL using managed identity example ([link](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-functions/functions-identity-access-azure-sql-with-managed-identity.md#configure-azure-function-sql-connection-string)), the connection string never contained the key.

**Comment by brandonh-msft** [comment]
That is the value eventually stuffed into `AzureWebJobsStorage` env var; not what's at play in the actual sample. The sample itself, when the Functions run, uses the Managed Identify for their operations which is what the sample is built to showcase.

**Comment by kiranpradeep** [comment]
@brandonh-msft It is hard to believe that kind of an argument. If the program does not use `AzureWebJobsStorage` env var, why it is even passed in? For e.g. can we pass in Terraform `random_string.result` [link](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) for  `AzureWebJobsStorage`? 

You may close this with out modification, but somebody else will come back with the same query.

**Comment by brandonh-msft** [comment]
If you did that, the function wouldn't start up because it uses the storage for its tracking purposes. 

I'd happily accept a PR pivoting the [backend storage connection to _also_ be MI](https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?toc=%2Fazure%2Fazure-functions%2Ftoc.json&tabs=portal%2Cdotnet) if you like!

**Comment by kiranpradeep** [comment]
> If you did that, the function wouldn't start up because it uses the storage for its tracking purposes.

ok so, the backing storage account is being with out MSI in the sample. And the MSI is active only for an independent storage account.

This repo begins with line //_In this sample you'll learn how you can rid yourself of all the cumbersome connection strings that often come with interacting with Azure Storage accounts._// which is not fully true. So at this point in time, my PR would be a correction to that line indicating to future readers, what is on MSI and what is not on MSI. 

I don't know how to utilize MSI for Azure Function on it's own backing storage account. It is not documented by Microsoft.

**Comment by brandonh-msft** [comment]
> I don't know how to utilize MSI for Azure Function on it's own backing storage account. It is not documented by Microsoft.

ah, but it is.
https://learn.microsoft.com/EN-us/azure/azure-functions/functions-identity-based-connections-tutorial#use-managed-identity-for-azurewebjobsstorage-preview

**Comment by kiranpradeep** [comment]
Thanks for the helpful link. But, Azure terraform provider is unaware of this preview mechanism and will continue to use `AzureWebJobsStorage`.  So until the provider improves, I don't think we can do anything cleanly (or azapi which would be much work).
